export const  orders = [
    {
      order: "SFP000006",
      customer: "champs",
      product: "Cameras",
      qty: 150,
      value: "-",
      status: "pending",
      shippedTotal: "0/0",
      tracking: "-",
      courier: "-",
      delivery: "-",
      address: "-",
    },
    {
      order: "SFP000005",
      customer: "Makvel",
      product: "test",
      qty: 1,
      value: "-",
      status: "cancelled",
      shippedTotal: "0/2 (2 pending)",
      tracking: "H54437102",
      courier: "dtdc",
      delivery: "-",
      address: "Industrial road, bangalore, karnataka",
    },
    {
      order: "SFP000004",
      customer: "Makvel",
      product: "636",
      qty: 1,
      value: "-",
      status: "shipped",
      shippedTotal: "2/3 (1 pending)",
      tracking: "TRK89558527",
      courier: "delhivery",
      delivery: "-",
      address: "Industrial road, bangalore, karnataka",
    },
    {
      order: "SFP000003",
      customer: "MakineniSoftinc",
      product: "Cameras cc",
      qty: 12,
      value: "-",
      status: "shipped",
      shippedTotal: "1/1",
      tracking: "TRK32394099",
      courier: "delhivery",
      delivery: "-",
      address: "askldf , laksjdf, Kerala1, kerala",
    },
    {
      order: "SFP000002",
      customer: "champs",
      product: "hardware",
      qty: 1,
      value: "-",
      status: "cancelled",
      shippedTotal: "1/1",
      tracking: "TRK22260011",
      courier: "dtdc",
      delivery: "-",
      address: "aksfas, bangalore, karnataka, India",
    },
    {
      order: "SFP000001",
      customer: "Makvel",
      product: "Cameras",
      qty: 100,
      value: "-",
      status: "shipped",
      shippedTotal: "2/4 (1 pending)",
      tracking: "TRK10069339",
      courier: "ecom",
      delivery: "-",
      address: "Industrial road, bangalore, karnataka",
    },
        {
      order: "SFP000006",
      customer: "champs",
      product: "Cameras",
      qty: 150,
      value: "-",
      status: "pending",
      shippedTotal: "0/0",
      tracking: "-",
      courier: "-",
      delivery: "-",
      address: "-",
    },
    {
      order: "SFP000005",
      customer: "Makvel",
      product: "test",
      qty: 1,
      value: "-",
      status: "cancelled",
      shippedTotal: "0/2 (2 pending)",
      tracking: "H54437102",
      courier: "dtdc",
      delivery: "-",
      address: "Industrial road, bangalore, karnataka",
    },
    {
      order: "SFP000004",
      customer: "Makvel",
      product: "636",
      qty: 1,
      value: "-",
      status: "shipped",
      shippedTotal: "2/3 (1 pending)",
      tracking: "TRK89558527",
      courier: "delhivery",
      delivery: "-",
      address: "Industrial road, bangalore, karnataka",
    },
    {
      order: "SFP000003",
      customer: "MakineniSoftinc",
      product: "Cameras cc",
      qty: 12,
      value: "-",
      status: "shipped",
      shippedTotal: "1/1",
      tracking: "TRK32394099",
      courier: "delhivery",
      delivery: "-",
      address: "askldf , laksjdf, Kerala1, kerala",
    },
    {
      order: "SFP000002",
      customer: "champs",
      product: "hardware",
      qty: 1,
      value: "-",
      status: "cancelled",
      shippedTotal: "1/1",
      tracking: "TRK22260011",
      courier: "dtdc",
      delivery: "-",
      address: "aksfas, bangalore, karnataka, India",
    },
    {
      order: "SFP000001",
      customer: "Makvel",
      product: "Cameras",
      qty: 100,
      value: "-",
      status: "shipped",
      shippedTotal: "2/4 (1 pending)",
      tracking: "TRK10069339",
      courier: "ecom",
      delivery: "-",
      address: "Industrial road, bangalore, karnataka",
    },
        {
      order: "SFP000006",
      customer: "champs",
      product: "Cameras",
      qty: 150,
      value: "-",
      status: "pending",
      shippedTotal: "0/0",
      tracking: "-",
      courier: "-",
      delivery: "-",
      address: "-",
    },
    {
      order: "SFP000005",
      customer: "Makvel",
      product: "test",
      qty: 1,
      value: "-",
      status: "cancelled",
      shippedTotal: "0/2 (2 pending)",
      tracking: "H54437102",
      courier: "dtdc",
      delivery: "-",
      address: "Industrial road, bangalore, karnataka",
    },
    {
      order: "SFP000004",
      customer: "Makvel",
      product: "636",
      qty: 1,
      value: "-",
      status: "shipped",
      shippedTotal: "2/3 (1 pending)",
      tracking: "TRK89558527",
      courier: "delhivery",
      delivery: "-",
      address: "Industrial road, bangalore, karnataka",
    },
    {
      order: "SFP000003",
      customer: "MakineniSoftinc",
      product: "Cameras cc",
      qty: 12,
      value: "-",
      status: "shipped",
      shippedTotal: "1/1",
      tracking: "TRK32394099",
      courier: "delhivery",
      delivery: "-",
      address: "askldf , laksjdf, Kerala1, kerala",
    },
    {
      order: "SFP000002",
      customer: "champs",
      product: "hardware",
      qty: 1,
      value: "-",
      status: "cancelled",
      shippedTotal: "1/1",
      tracking: "TRK22260011",
      courier: "dtdc",
      delivery: "-",
      address: "aksfas, bangalore, karnataka, India",
    },
    {
      order: "SFP000001",
      customer: "Makvel",
      product: "Cameras",
      qty: 100,
      value: "-",
      status: "shipped",
      shippedTotal: "2/4 (1 pending)",
      tracking: "TRK10069339",
      courier: "ecom",
      delivery: "-",
      address: "Industrial road, bangalore, karnataka",
    },
  ];